index:
    path: /
    defaults: { _controller: 'App\Controller\PageController::actionIndex'}

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin