<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0nnmhem\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0nnmhem/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0nnmhem.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0nnmhem\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container0nnmhem\srcDevDebugProjectContainer(array(
    'container.build_hash' => '0nnmhem',
    'container.build_id' => '1509cced',
    'container.build_time' => 1517142937,
));
